apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "goserver.fullname" . }}
spec:
    replicas: 1
    selector:
      matchLabels:
        {{- include "goserver.selectorLabels" . | nindent 8 }}
    template:
      metadata:
        labels:
            {{- include "goserver.selectorLabels" . | nindent 10 }}
      spec:
        containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        # This app listens on port 8080 for web traffic by default.
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          env:
          - name: DATABASE_URL
            valueFrom:
                secretKeyRef:
                    name: {{ .Values.env.secretName }}
                    key: {{ .Values.env.secretKey }}
        - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
          image:  "{{ .Values.sqlsidecar.repository }}:{{ .Values.sqlsidecar.tag }}"
          command:
            - /cloud_sql_proxy

            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            # - "-ip_address_types=PRIVATE"

            # Replace DB_PORT with the port the proxy should listen on
            # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
            - -instances={{ .Values.sqlsidecar.sql_connection_name }}=tcp:{{ .Values.sqlsidecar.port }}

        # [START cloud_sql_proxy_k8s_volume_mount]
            # This flag specifies where the service account key can be found
            - -credential_file=/secrets/{{ .Values.sqlsidecar.secretKey }}
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          volumeMounts:
          - name: cloudsql-sa-secret-volume
            mountPath: /secrets/
            readOnly: true
            # [END cloud_sql_proxy_k8s_volume_mount]
        # [START cloud_sql_proxy_k8s_volume_secret]
        volumes:
        - name: cloudsql-sa-secret-volume
          secret:
            secretName: {{ .Values.sqlsidecar.secretName }}
        # [START cloud_sql_proxy_k8s_volume_secret]