project_id = "sandbox-mtm"
region = "us-central1"
compute_engine_service_account = "vorto-kubernetes"
# sql_user = "postgres"
# sql_pwd = "postgres"
# db_url = "dbname=public host=localhost user=postgres password=postgres port=5432 sslmode=disable"