project_id = "sandbox-mtm"
region = "us-central1"
cluster_name_suffix = ""
compute_engine_service_account = "vorto-kubernetes"
network = "default"
subnetwork = "default"
ip_range_pods = "10.28.0.0/14"
ip_range_services = "us-central1-01-gke-01-services"