steps:
- name: 'golang'
  args: ['go', 'build', '.']
  env: ['GOPATH=/workspace/go/src/go_server', 'GO111MODULE=on']
- name: 'golang'
  args: ['go', 'test']
  env: ['GOPATH=/workspace/go/src/go_server', 'GO111MODULE=on']
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go_server', '.']
  dir: 'go'
images: [gcr.io/$PROJECT_ID/go_server]