steps:
# - dir: 'go/src'
- name: 'golang'
  args: ['go', 'mod', 'init', 'src/go_server']
- name: 'golang'
  entrypoint: 'go'
  args: ['install', 'go_server']
  env: ['PROJECT_ROOT=src/go_server']
# - name: 'gcr.io/cloud-builders/go'
#   args: ['test', 'go_server']
#   env: ['PROJECT_ROOT=src/go_server']
# - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/go_server', '.']
# - name: 'gcr.io/cloud-builders/docker'
#     args: ['run', 'gcr.io/$PROJECT_ID/go_server']
# images: [gcr.io/$PROJECT_ID/go_server]