# steps:
# - name: 'golang'
#   args: ['go', 'build', '.']
#   env: ['GOPATH=/workspace/go/src/go_server']
# - name: 'golang'
#   args: ['go', 'test']
#   env: ['GOPATH=/workspace/go/src/go_server']
# - name: 'docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/go_server', '.']
#   dir: 'go'
# images: [gcr.io/$PROJECT_ID/go_server]
steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', 'go_server']
    env: ['GOPATH=/go']
    dir: 'go'
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', 'go_server']
    env: ['GOPATH=/go']
    dir: 'go'
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '--tag=gcr.io/$PROJECT_ID/hello', '.']
  # images: ['gcr.io/$PROJECT_ID/hello']