steps:
- name: 'golang'
  args: ['go', 'build', '.']
  dir: 'go/src/go_server'
- name: 'golang'
  args: ['go', 'test']
  dir: 'go/src/go_server'
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go_server', '.']
  dir: 'go'
images: [gcr.io/$PROJECT_ID/go_server]
